use game;
db.dropDatabase();

db.Cards.insertMany([
  {
    id: 10,
    colour: "blue",
    number: 10,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 11,
    colour: "blue",
    number: 1,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 12,
    colour: "blue",
    number: 2,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 13,
    colour: "blue",
    number: 3,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 14,
    colour: "blue",
    number: 4,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 15,
    colour: "blue",
    number: 5,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 16,
    colour: "blue",
    number: 6,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 17,
    colour: "blue",
    number: 7,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 18,
    colour: "blue",
    number: 8,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 19,
    colour: "blue",
    number: 9,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 20,
    colour: "red",
    number: 10,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 21,
    colour: "red",
    number: 1,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 22,
    colour: "red",
    number: 2,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 23,
    colour: "red",
    number: 3,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 24,
    colour: "red",
    number: 4,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 25,
    colour: "red",
    number: 5,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 26,
    colour: "red",
    number: 6,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 27,
    colour: "red",
    number: 7,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 28,
    colour: "red",
    number: 8,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 29,
    colour: "red",
    number: 9,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 30,
    colour: "green",
    number: 10,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 31,
    colour: "green",
    number: 1,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 32,
    colour: "green",
    number: 2,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 33,
    colour: "green",
    number: 3,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 34,
    colour: "green",
    number: 4,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 35,
    colour: "green",
    number: 5,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 36,
    colour: "green",
    number: 6,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 37,
    colour: "green",
    number: 7,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 38,
    colour: "green",
    number: 8,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 39,
    colour: "green",
    number: 9,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 40,
    colour: "yellow",
    number: 10,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 41,
    colour: "yellow",
    number: 1,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 42,
    colour: "yellow",
    number: 2,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 43,
    colour: "yellow",
    number: 3,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 44,
    colour: "yellow",
    number: 4,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 45,
    colour: "yellow",
    number: 5,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 46,
    colour: "yellow",
    number: 6,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 47,
    colour: "yellow",
    number: 7,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 48,
    colour: "yellow",
    number: 8,
    url: 'http://localhost:3000/images/green_1.png',
  },
  {
    id: 49,
    colour: "yellow",
    number: 9,
    url: 'http://localhost:3000/images/green_1.png',
  },
]);

db.CardsMisc.insertMany([
  {
    name: "back",
    url: 'http://localhost:3000/images/back.png',
  },
]);
